# Configuration for the CKG + PubMedKG GraphRAG project.

project:
  name: dual-kg-graphrag
  region: us-east-1
  environment: dev

paths:
  local_data_dir: data/local
  graph_dir: data/graph
  embeddings_dir: data/embeddings
  vector_index_path: data/embeddings/vector.index
  logs_dir: logs

s3:
  bucket: your-s3-bucket-name
  prefixes:
    raw: raw/
    staging: staging/
    graph: graph/

neptune:
  endpoint: https://example.cluster-ro-id.neptune.amazonaws.com:8182
  iam_role_arn: arn:aws:iam::123456789012:role/NeptuneLoadFromS3
  graph_format: openCypher
  max_concurrency: 2

open_search:
  endpoint: https://search-your-collection-id.us-east-1.aoss.amazonaws.com
  collection_name: dual-kg-vectors
  index_name: graphrag_nodes
  embedding_dimension: 768

embedding_model:
  document_model: sentence-transformers/all-MiniLM-L12-v2
  node_model: sentence-transformers/all-MiniLM-L12-v2

llm:
  provider: openai-compatible
  api_base: http://localhost:8001/v1
  api_key: changeme
  model_name: meta-llama/Meta-Llama-3-8B-Instruct
  temperature: 0.2
  max_new_tokens: 512

pyg_rag:
  enabled: true
  model: node2vec
  dim: 64
  walks_per_node: 5
  walk_length: 20
  context_size: 10
  epochs: 1
  learning_rate: 0.01
  top_facts: 40

retrieval:
  top_k: 8
  expansion_hops: 2
  prune_max_nodes: 40
  prune_max_degree: 10
  namespaces:
    include:
      - CKG_
      - PKG_

ckg_ingest:
  input_dir: data/local/ckg/processed
  output_dir: data/graph/ckg
  nodes_glob: ckg_nodes_*.csv
  relationships_glob: ckg_relationships_*.csv

pkg_ingest:
  input_dir: data/local/pubmedkg/processed
  output_dir: data/graph/pkg
  publications_file: pubmed_publications.csv
  mentions_file: pubmed_mentions.csv
  citations_file: pubmed_citations.csv

neptune_loader:
  output_dir: configs
  file_name_prefix: neptune_loader

vector_store:
  include_types:
    - CKG_* 
    - PKG_*

app:
  demo_questions: configs/demo_questions.yaml



